# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
START_PAUSED = true #false
ADMIN_CAN_ADD_PLANETS = true
PLANET_TRANSFER_ENABLED = false
WORLD_RADIUS_LOCKED = false
WORLD_RADIUS_MIN = 103000 #53000

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = false
PLANETHASH_KEY =115000 # 6279
SPACETYPE_KEY =1161 #6280
BIOMEBASE_KEY = 117123 #  6271
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 16384 # must be a power of two no greater than 16384

#############
# Artifacts #
#############
TOKEN_MINT_END_TIMESTAMP = 2023-10-05T04:00:00.000Z # Mon Oct 04 2022 21:00:00 GMT-0700 (Pacific Daylight Time)
ARTIFACT_POINT_VALUES = [
  0,
  2000,
  10000,
  200000,
  3000000,
  20000000
]

# ARTIFACT_POINT_VALUES = [
#   0,
#   0,
#   0,
#   0,
#   0,
#   0
# ]
PHOTOID_ACTIVATION_DELAY = 600 # seconds
STELLAR_ACTIVATION_DELAY = 0 # seconds
##############
# Space junk #
##############
SPACE_JUNK_ENABLED = true #false
# Total amount of space junk a player can take on. This can be overridden at runtime by updating this value for a specific player in storage.
SPACE_JUNK_LIMIT = 3000
# The amount of junk that each level of planet gives the player when moving to it for the first time.
PLANET_LEVEL_JUNK = [20, 25, 30, 35, 40, 45, 50, 55, 60, 65]
# The speed boost a movement receives when abandoning a planet.
ABANDON_SPEED_CHANGE_PERCENT = 150
# The range boost a movement receives when abandoning a planet.
ABANDON_RANGE_CHANGE_PERCENT = 150

#################
# Capture zones #
#################
CAPTURE_ZONES_ENABLED = true
# How often zones change location. Max 255.
CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL = 255
# How big the capture zones are
CAPTURE_ZONE_RADIUS = 1000
# The amount of score each planet level gives for capturing
CAPTURE_ZONE_PLANET_LEVEL_SCORE = [
  0,
  0,
  1_000,
  2_500,
  5_000,
  10_000,
  100_000,
  200_000,
  500_000,
  1_000_000
]
# After invading, the number of blocks you need to hold a planet for before capturing
CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED = 10 # 255 # MyTodo: need to change to a non-zero value
# Number of capture zones that spawn each time they generate
CAPTURE_ZONES_PER_5000_WORLD_RADIUS = 5  # 3

######################
# Game configuration #
######################
MAX_NATURAL_PLANET_LEVEL = 9
MAX_ARTIFACT_PER_PLANET = 5
MAX_SENDING_PLANET = 8
MAX_RECEIVING_PLANET = 8
TIME_FACTOR_HUNDREDTHS = 500  #100 # speedup/slowdown game
PERLIN_THRESHOLD_1 = 14
PERLIN_THRESHOLD_2 = 15
PERLIN_THRESHOLD_3 = 19
INIT_PERLIN_MIN = 13
INIT_PERLIN_MAX = 14
SPAWN_RIM_AREA = 0
BIOME_THRESHOLD_1 = 15
BIOME_THRESHOLD_2 = 17
#  The chance for a planet to be a specific level.
#  Each index corresponds to a planet level (index 5 is level 5 planet).
#  The lower the number the lower the chance.
#  Note: This does not control if a planet spawns or not, just the level
#  when it spawns.
PLANET_LEVEL_THRESHOLDS = [
  16_777_216,
  4_194_292,
  1_048_561,
  262_128,
  65_520,
  16_368,
  4_080,
  1_008,
  240,
  48
]
PLANET_RARITY = 16384
# How much score silver gives when withdrawing.
# Expressed as a percentage integer.
# (100 is 100%)
SILVER_SCORE_VALUE = 100
LOCATION_REVEAL_COOLDOWN = 86400 # seconds
PLANET_TYPE_WEIGHTS = [
  [
    [10, 0, 0, 0, 0],
    [13, 2, 0, 10, 0],
    [13, 2, 0, 10, 0],
    [13, 2, 0, 0, 10],
    [13, 2, 0, 0, 10],
    [13, 2, 0, 0, 10],
    [13, 2, 0, 0, 10],
    [13, 2, 0, 0, 10],
    [13, 2, 0, 0, 10],
    [13, 2, 0, 0, 10],
  ],
  [
    [10, 0, 0, 0, 0],
    [13, 2, 10, 0, 0],
    [12, 2, 10, 1, 0],
    [11, 2, 10, 1, 10],
    [12, 2, 10, 0, 10],
    [12, 2, 10, 0, 10],
    [12, 2, 10, 0, 10],
    [12, 2, 10, 0, 10],
    [12, 2, 10, 0, 10],
    [12, 2, 10, 0, 10],
  ],
  [
    [10, 0, 0, 0, 0],
    [10, 4, 2, 0, 0],
    [10, 4, 10, 10, 0],
    [8, 4, 10, 2, 10],
    [8, 4, 10, 2, 10],
    [8, 4, 10, 2, 10],
    [8, 4, 10, 2, 10],
    [8, 4, 10, 2, 10],
    [8, 4, 10, 2, 10],
    [8, 4, 10, 2, 10],
  ],
  [
    [10, 0, 0, 0, 0],
    [11, 4, 10, 0, 0],
    [11, 4, 10, 0, 0],
    [7, 4, 2, 2, 10],
    [7, 4, 2, 2, 10],
    [7, 4, 2, 2, 10],
    [7, 4, 2, 2, 10],
    [7, 4, 2, 2, 10],
    [7, 4, 2, 2, 10],
    [7, 4, 2, 2, 10],
  ],
]
ROUND_END_REWARDS_BY_RANK=[
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
]


[initializers.SPACESHIPS]
GEAR = false
MOTHERSHIP = true
TITAN = true
CRESCENT = true
WHALE = false

##########################
# Planets to add to game #
##########################
