# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
START_PAUSED = true #false
ADMIN_CAN_ADD_PLANETS = true
PLANET_TRANSFER_ENABLED = false
WORLD_RADIUS_LOCKED = false
WORLD_RADIUS_MIN = 150_000


##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = false
PLANETHASH_KEY = 2354
SPACETYPE_KEY = 136
BIOMEBASE_KEY = 6119
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 8192 #16384 # must be a power of two no greater than 16384

#############
# Artifacts #
#############
TOKEN_MINT_END_TIMESTAMP = 2024-08-17T14:00:00.000Z
ARTIFACT_POINT_VALUES = [
  0,
  2000,
  10000,
  200000,
  3000000,
  20000000
]

# ARTIFACT_POINT_VALUES = [
#   0,
#   0,
#   0,
#   0,
#   0,
#   0
# ]
PHOTOID_ACTIVATION_DELAY = 14400 # seconds
STELLAR_ACTIVATION_DELAY = 0 # seconds
##############
# Space junk #
##############
SPACE_JUNK_ENABLED = false
# Total amount of space junk a player can take on. This can be overridden at runtime by updating this value for a specific player in storage.
SPACE_JUNK_LIMIT = 3000
# The amount of junk that each level of planet gives the player when moving to it for the first time.
PLANET_LEVEL_JUNK = [20, 25, 30, 35, 40, 45, 50, 55, 60, 65]
# The speed boost a movement receives when abandoning a planet.
ABANDON_SPEED_CHANGE_PERCENT = 150
# The range boost a movement receives when abandoning a planet.
ABANDON_RANGE_CHANGE_PERCENT = 150

#################
# Capture zones #
#################
CAPTURE_ZONES_ENABLED = false
# How often zones change location. Max 255.
CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL = 255
# How big the capture zones are
CAPTURE_ZONE_RADIUS = 1000
# The amount of score each planet level gives for capturing
CAPTURE_ZONE_PLANET_LEVEL_SCORE = [
  0,
  0,
  1_000,
  2_500,
  5_000,
  10_000,
  100_000,
  200_000,
  500_000,
  1_000_000
]
# After invading, the number of blocks you need to hold a planet for before capturing
CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED =  255 # MyTodo: need to change to a non-zero value
# Number of capture zones that spawn each time they generate
CAPTURE_ZONES_PER_5000_WORLD_RADIUS = 5  # 3


######################
# Game configuration #
######################
MAX_NATURAL_PLANET_LEVEL = 9
MAX_ARTIFACT_PER_PLANET = 5
MAX_SENDING_PLANET = 8
MAX_RECEIVING_PLANET = 8
TIME_FACTOR_HUNDREDTHS = 200  # speedup/slowdown game
PERLIN_THRESHOLD_1 = 14
PERLIN_THRESHOLD_2 = 15
PERLIN_THRESHOLD_3 = 19
# NOTE: Finding a home planet requires Perlin verification
INIT_PERLIN_MIN = 1
INIT_PERLIN_MAX = 31
SPAWN_RIM_AREA = 0 #2106750000 => min radius around 46239
BIOME_THRESHOLD_1 = 15
BIOME_THRESHOLD_2 = 17
#  The chance for a planet to be a specific level.
#  Each index corresponds to a planet level (index 5 is level 5 planet).
#  The lower the number the lower the chance.
#  Note: This does not control if a planet spawns or not, just the level
#  when it spawns.
PLANET_LEVEL_THRESHOLDS = [
  16_777_216,
  4_194_292,
  1_048_561,
  262_128,
  65_520,
  30_000,#16_368,
  8_000,#4_080,
  4_000,#1_008,
  500,#240,
  100,#48
]


PLANET_RARITY =  16384
# How much score silver gives when withdrawing.
# Expressed as a percentage integer.
# (100 is 100%)
SILVER_SCORE_VALUE = 100
LOCATION_REVEAL_COOLDOWN = 86400 # seconds
CLAIM_PLANET_COOLDOWN = 14400 # seconds
CLAIM_END_TIMESTAMP = 2024-08-17T14:00:00.000Z

# NOTE: leave this config, but don't work in contract
ACTIVATE_ARTIFACT_COOLDOWN = 600
BUY_ARTIFACT_COOLDOWN  = 43200


BURN_END_TIMESTAMP = 2024-08-17T14:00:00.000Z
BURN_PLANET_COOLDOWN = 7200 # seconds
PINK_PLANET_COOLDOWN = 7200 #seconds

BURN_PLANET_LEVEL_EFFECT_RADIUS = [
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500
]

# NOTE: the value should be same, or client will have bugs
BURN_PLANET_REQUIRE_SILVER_AMOUNTS = [
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000
]

KARDASHEV_END_TIMESTAMP = 2024-08-17T14:00:00.000Z
KARDASHEV_PLANET_COOLDOWN =  7200 # seconds
BLUE_PLANET_COOLDOWN = 7200 #seconds

KARDASHEV_EFFECT_RADIUS = [
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500,
  2500
]

# NOTE: the value should be same, or client will have bugs
KARDASHEV_REQUIRE_SILVER_AMOUNTS = [
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000,
  150000
]




BLUE_PANET_REQUIRE_SILVER_AMOUNTS = [
  10000,
  10000,
  10000,
  10000,
  10000,
  10000,
  10000,
  10000,
  10000,
  10000
]

#################
# Planet Adjust #
#################

# MAX_LEVEL_DIST=[70000, 60000, 50000, 40000, 30000]

MAX_LEVEL_DIST =[131250, 112500, 93750, 75000, 56250]

MAX_LEVEL_LIMIT=[9, 5, 6, 7, 8, 9]
MIN_LEVEL_BIAS = [0, 0, 0, 0, 0, 1]

PLANET_TYPE_WEIGHTS = [
  [
    [1, 0, 0, 0, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [13, 2, 1, 0, 0],
    [12, 2, 1, 1, 0],
    [11, 2, 1, 1, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [10, 4, 2, 0, 0],
    [10, 4, 1, 1, 0],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [11, 4, 1, 0, 0],
    [11, 4, 1, 0, 0],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
  ],
]


ROUND_END_REWARDS_BY_RANK=[
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
]

ENTRY_FEE= 0 # gwei # 2_000_000  # 0.002 eth

# not include PinkShip yet
[initializers.SPACESHIPS]
GEAR = true
MOTHERSHIP = false
TITAN = false
CRESCENT = false
WHALE = false
PINKSHIP = false



##########################
# Planets to add to game #
##########################
[[planets]]
  x = 0
  y = 0
  level = 9
  planetType = 0
  requireValidLocationId = false
  revealLocation = true
